'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const api=require('./collect-logread-version8.cjs'),v4=require('./validate-logread-browser-v4.cjs'),v2=require('./validate-logread-browser-v2.cjs'),b0=require('./prepare-d4b.cjs');
const enc=x=>Buffer.from(JSON.stringify(x)),copy=x=>x.map(f=>({...f,bytes:Buffer.from(f.bytes)})),clone=structuredClone;
const headFiles=[{name:'appsscript.json',bytes:enc({timeZone:'Europe/Paris'})},{name:'Base.gs',bytes:Buffer.from('base')}];
const v8Files=[{name:'appsscript.json',bytes:enc({timeZone:'Europe/Paris',webapp:{access:'ANYONE',executeAs:'USER_ACCESSING'}})},{name:'Base.gs',bytes:Buffer.from('base')}];
const baseline={versions:[{versionNumber:8,description:'old'}],deployments:[{deploymentId:'HEAD',description:'head'},{deploymentId:'OLD-OMcZ9gl',versionNumber:8,description:'ACCESS V1.4.0-rc.5'}]};
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'aks-v5-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const dirs={};for(const n of [api.PIN.campaign,api.PIN.readSession,api.PIN.technicalSession,api.PIN.priorSession,api.PIN.v2Session,api.PIN.v3Session,api.PIN.v4Session,'clasp']){dirs[n]=path.join(root,n);fs.mkdirSync(dirs[n]);}const e={dir:dirs[api.PIN.campaign],readSession:dirs[api.PIN.readSession],backup:copy(headFiles),candidate:[...copy(headFiles),{name:'New.gs',bytes:Buffer.from('new')}],lists:clone(baseline)},t0={session:dirs[api.PIN.technicalSession],resultSha256:'d'.repeat(64)},p={session:dirs[api.PIN.priorSession],restoredResultSha256:'e'.repeat(64)},v={session:dirs[api.PIN.v2Session],restoredResultSha256:'f'.repeat(64)},z={session:dirs[api.PIN.v3Session],restoredResultSha256:'a'.repeat(64)},q={session:dirs[api.PIN.v4Session],restoredResultSha256:'b'.repeat(64)},current=clone(baseline),o={mode:'LocalCheck','package-run':dirs[api.PIN.campaign],'read-session':dirs[api.PIN.readSession],'technical-session':dirs[api.PIN.technicalSession],'prior-session':dirs[api.PIN.priorSession],'v2-session':dirs[api.PIN.v2Session],'v3-session':dirs[api.PIN.v3Session],'v4-session':dirs[api.PIN.v4Session],'clasp-package':dirs.clasp};current.versions.push({versionNumber:9,description:v2.VERSION_DESCRIPTION});return{root,dirs,e,t:t0,p,v,z,q,current,o};}
function deps(f){return{loadEvidence:()=>f.e,loadTechnical:()=>f.t,loadPriorAttempt:()=>f.p,loadV2Attempt:()=>f.v,loadV3Attempt:()=>f.z,loadV4Attempt:()=>f.q,claspEntry:()=>''};}
function io(f,head=copy(headFiles),version8=copy(v8Files)){return{read(label,n){return{dir:path.join(f.root,label),files:n===8?copy(version8):copy(head),lists:clone(f.current)};}};}
function record(session,event){fs.writeFileSync(path.join(session,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));}
function v4Evidence(f){fs.writeFileSync(path.join(f.q.session,'session.json'),JSON.stringify({binding:v4.binding(f.e,f.t,f.p,f.v,f.z)}));const common={revision:'LOGREAD-browser-v4-r1',candidate:api.PIN.candidate,packageSha256:api.PIN.package,preflightSession:f.e.readSession,technicalSession:f.t.session,priorSession:f.p.session,v2Session:f.v.session,v3Session:f.z.session,v3RestoredResultSha256:f.z.restoredResultSha256,retainedVersionNumber:9,webAppDeploymentSuffix:'OMcZ9gl',localEvidenceVerified:true,googleReadAttempted:true,googleWriteAttempted:true,browserAuthorized:true,versionCreationAuthorized:false,deploymentCreationAuthorized:false,session:f.q.session,webAppUpdatedToVersion9:true,deploymentUpdateMetadataChanged:true,versionRetained:true};fs.writeFileSync(path.join(f.q.session,'result-00000000-0000-0000-0000-000000000001.json'),JSON.stringify({...common,status:'MANUAL_RECOVERY_REQUIRED',failure:'OPERATOR_STEP_NOT_CONFIRMED',webAppRestoredToVersion8:false,deploymentConfigurationRestored:false}));fs.writeFileSync(path.join(f.q.session,'result-00000000-0000-0000-0000-000000000002.json'),JSON.stringify({...common,status:'RESTORED_WEBAPP_VERSION_8_NOT_PASSED',failure:'LOGREAD_BROWSER_V4_STOPPED',webAppRestoredToVersion8:true,deploymentConfigurationRestored:true}));for(const x of ['CANDIDATE_EXACT','WEBAPP_UPDATED_TO_9','PRIVATE_ACTIVATED','OAUTH_REVIEWED_INTENT','PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED','WEBAPP_RESTORED_TO_8','RESTORED_EXACT','CODE_RESTORED'])record(f.q.session,x);}
test('authorization is read-only and package bound',()=>assert.equal(api.AUTHORIZATION,'LOGREAD-VERSION8-READONLY-'+api.PIN.package));
test('CLI accepts only closed paired arguments',t=>{const f=fixture(t),args=Object.entries(f.o).flatMap(([k,v])=>['--'+k,v]);assert.equal(api.parseArgs(args).mode,'LocalCheck');assert.throws(()=>api.parseArgs([...args,'--bad','x']));assert.throws(()=>api.parseArgs([...args,'--mode','LocalCheck']));});
test('LocalCheck performs no native call or output write',async t=>{const f=fixture(t);let n=0;const r=await api.main(f.o,{...deps(f),native:()=>n++});assert.equal(r.status,'LOGREAD_VERSION8_READONLY_LOCAL_CHECK_ONLY');assert.equal(r.googleReadAttempted,false);assert.equal(n,0);});
test('authorization is rejected before evidence',async t=>{const f=fixture(t);let n=0;await assert.rejects(()=>api.main({...f.o,mode:'GoogleReadOnly',output:path.join(f.root,'out')},{loadEvidence:()=>n++}),/AUTHORIZATION/);assert.equal(n,0);});
test('V4 evidence requires failed attempt and restored configuration',t=>{const f=fixture(t);v4Evidence(f);assert.equal(api.loadV4Attempt(f.q.session,f.e,f.t,f.p,f.v,f.z).session,f.q.session);record(f.q.session,'OAUTH_REVIEWED');assert.throws(()=>api.loadV4Attempt(f.q.session,f.e,f.t,f.p,f.v,f.z),/FALSE_BROWSER_PASS/);});
test('manifest distinguishes absent and valid Web App configuration',()=>{assert.deepEqual(api.webapp({}),{present:false,access:null,executeAs:null});assert.deepEqual(api.webapp({webapp:{access:'ANYONE',executeAs:'USER_ACCESSING'}}),{present:true,access:'ANYONE',executeAs:'USER_ACCESSING'});});
test('manifest rejects malformed Web App configuration',()=>assert.throws(()=>api.webapp({webapp:{access:'ANYONE'}}),/INVALID/));
test('collection reports exact manifest delta without Google write',t=>{const f=fixture(t),o={...f.o,mode:'GoogleReadOnly',output:path.join(f.root,'out'),authorization:api.AUTHORIZATION};const r=api.collect(o,f.e,f.t,f.p,f.v,f.z,f.q,'',{io:io(f)});assert.equal(r.status,'VERSION8_MANIFEST_COLLECTED_REVIEW_REQUIRED');assert.equal(r.googleWriteAttempted,false);assert.equal(r.manifestsExact,false);assert.equal(r.headWebapp.present,false);assert.equal(r.version8Webapp.present,true);assert.ok(fs.existsSync(path.join(r.session,'report.json')));});
test('collection refuses a non-restored HEAD',t=>{const f=fixture(t),o={...f.o,mode:'GoogleReadOnly',output:path.join(f.root,'out'),authorization:api.AUTHORIZATION},changed=[...copy(headFiles),{name:'Other.gs',bytes:Buffer.from('x')}];assert.throws(()=>api.collect(o,f.e,f.t,f.p,f.v,f.z,f.q,'',{io:io(f,changed)}),/HEAD_NOT_RESTORED/);});
test('collection refuses inventory drift between reads',t=>{const f=fixture(t),o={...f.o,mode:'GoogleReadOnly',output:path.join(f.root,'out'),authorization:api.AUTHORIZATION},x=io(f),read=x.read.bind(x);x.read=(label,n)=>{const r=read(label,n);if(n===8)r.lists.versions.push({versionNumber:10});return r;};assert.throws(()=>api.collect(o,f.e,f.t,f.p,f.v,f.z,f.q,'',{io:x}),/INVENTORY/);});
test('transport emits only HEAD and version 8 read commands',t=>{const f=fixture(t),session=path.join(f.root,'transport');fs.mkdirSync(session);const calls=[];const run=(_c,args,cwd)=>{calls.push(args.slice(2));if(args[2]==='list-versions')return Buffer.from(JSON.stringify(f.current.versions));if(args[2]==='list-deployments')return Buffer.from(JSON.stringify(f.current.deployments));if(args[2]==='pull'){fs.rmSync(path.join(cwd,'src'),{recursive:true});b0.materialize(path.join(cwd,'src'),headFiles);return Buffer.from(JSON.stringify({pulledFiles:headFiles.map(x=>x.name),deletedFiles:[]}));}};const x=api.makeTransport('/entry',session,run);x.read('head',null);assert.deepEqual(calls,[['list-versions'],['list-deployments'],['pull'],['list-versions'],['list-deployments']]);});
test('output cannot enter an evidence root',t=>{const f=fixture(t);assert.throws(()=>api.output(path.join(f.e.dir,'nested'),[f.e.dir]),/PROTECTED/);});
test('arbitrary errors are redacted',()=>assert.equal(api.safeError(Error('https://secret/token')),'LOGREAD_VERSION8_READONLY_STOPPED'));
