'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const api=require('./validate-logread-webapp-browser.cjs'),b0=require('./prepare-d4b.cjs');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),clone=x=>structuredClone(x),cloneFiles=x=>x.map(row=>({name:row.name,bytes:Buffer.from(row.bytes)}));
const backup=[{name:'appsscript.json',bytes:Buffer.from('{"runtimeVersion":"V8"}')},{name:'Old.gs',bytes:Buffer.from('old')}],candidate=[...backup,{name:'New.gs',bytes:Buffer.from('new')}];
const baseline={versions:Array.from({length:9},(_,i)=>({versionNumber:i+1,description:'v'+(i+1)})),deployments:[{deploymentId:'head',description:'Head'},{deploymentId:'AKfycbx-OMcZ9gl',versionNumber:8,description:'Application Web'}]};
function roots(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'webapp-browser-r3-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const d={root,packageDir:path.join(root,api.PIN.campaign),version8:path.join(root,api.PIN.version8Session),read:path.join(root,api.PIN.readSession),technical:path.join(root,api.PIN.technicalSession),attempt:path.join(root,api.PIN.attemptSession),r2:path.join(root,api.PIN.r2Session),clasp:path.join(root,'clasp')};for(const v of Object.values(d).slice(1))fs.mkdirSync(v,{recursive:true});fs.writeFileSync(path.join(d.clasp,'bin.cjs'),'');fs.writeFileSync(path.join(d.clasp,'package.json'),JSON.stringify({name:'@google/clasp',version:'3.3.0',bin:'bin.cjs'}));return d;}
function evidence(d){return{dir:d.packageDir,version8Session:d.version8,readSession:d.read,readReportSha256:hash('read'),candidate:cloneFiles(candidate),backup:cloneFiles(backup),lists:clone(baseline)};}
function technical(d){return{session:d.technical,resultSha256:hash('technical')};}
function attempt(d){return{session:d.attempt,failedResultSha256:hash('failed'),restoredResultSha256:hash('restored')};}
function r2Attempt(d){return{session:d.r2,resultSha256:hash('r2-result'),canonicalInventorySha256:hash('r2-canonical')};}
function options(d){return{mode:'LocalCheck','package-run':d.packageDir,'version8-session':d.version8,'read-session':d.read,'technical-session':d.technical,'attempt-session':d.attempt,'r2-session':d.r2,'clasp-package':d.clasp};}
function v10(webAppVersion=8){const x=clone(baseline);x.versions.push({versionNumber:10,description:api.VERSION_DESCRIPTION});x.deployments[1].versionNumber=webAppVersion;return x;}
function writeEvent(dir,event){fs.writeFileSync(path.join(dir,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));}
function attemptFixture(d,e,t){fs.writeFileSync(path.join(d.attempt,'session.json'),JSON.stringify({binding:api.attemptBinding(e,t)}));for(const event of ['CANDIDATE_PUSH_INTENT','CANDIDATE_EXACT','VERSION_10_CREATE_INTENT','RESTORE_PUSH_INTENT','RESTORED_EXACT','CODE_RESTORED'])writeEvent(d.attempt,event);const common={revision:'LOGREAD-webapp-browser-r1',target:b0.TARGET,candidate:api.PIN.candidate,packageSha256:api.PIN.source,packageArchiveSha256:api.PIN.archive,packageReportSha256:api.PIN.packageReport,version8ReportSha256:api.PIN.version8Report,preflightReportSha256:e.readReportSha256,preflightSession:e.readSession,technicalSession:t.session,technicalResultSha256:t.resultSha256,baselineVersionsCount:9,baselineDeploymentsCount:2,baselineWebAppVersion:8,plannedVersionNumber:10,versionDescription:api.VERSION_DESCRIPTION,webAppDeploymentSuffix:'OMcZ9gl',localEvidenceVerified:true,googleReadAttempted:true,googleWriteAttempted:true,browserAuthorized:true,versionCreationAuthorized:true,deploymentUpdateAuthorized:true,newDeploymentAuthorized:false,session:d.attempt};const failed={...common,status:'RESTORE_REQUIRED',failure:'VERSION_CREATE_NOT_EXACT',versionNumber:null,versionRetained:false,immutableVersion10Verified:false,webAppUpdatedToVersion10:false,webAppRestoredToVersion8:false,deploymentConfigurationRestored:false,newDeploymentCreated:false};const restored={...common,status:'RESTORED_WEBAPP_VERSION_8_VERSION_10_RETAINED_BROWSER_REVIEW_REQUIRED',failure:null,versionNumber:10,versionRetained:true,immutableVersion10Verified:false,webAppUpdatedToVersion10:false,webAppRestoredToVersion8:true,deploymentConfigurationRestored:true,newDeploymentCreated:false};const fb=Buffer.from(JSON.stringify(failed)),rb=Buffer.from(JSON.stringify(restored));fs.writeFileSync(path.join(d.attempt,'result-'+crypto.randomUUID()+'.json'),fb);fs.writeFileSync(path.join(d.attempt,'result-'+crypto.randomUUID()+'.json'),rb);return{failed:hash(fb),restored:hash(rb)};}
test('R3 is bound to both restored attempts and uses a new exact authorization',()=>{assert.equal(api.PIN.attemptSession,'logread-webapp-browser-fcC70e');assert.equal(api.PIN.r2Session,'logread-webapp-browser-r2-6OZtg9');assert.equal(api.AUTHORIZATION,'LOGREAD-WEBAPP-BROWSER-R3-RESUME-'+api.PIN.source);assert.equal(api.PIN.candidateVersion,10);});
test('CLI removes Execute and permits only LocalCheck, Resume and Restore',t=>{const d=roots(t),o=options(d),args=Object.entries(o).flatMap(([k,v])=>['--'+k,v]);assert.equal(api.parseArgs(args).mode,'LocalCheck');assert.throws(()=>api.parseArgs(args.flatMap((x,i)=>i===1?['Execute']: [x])),/INVALID/);assert.throws(()=>api.parseArgs([...args,'--output',d.root]));});
test('Resume and Restore reject missing authorization before evidence access',async t=>{const d=roots(t),o=options(d);let touched=0;for(const mode of ['Resume','Restore'])await assert.rejects(()=>api.main({...o,mode,output:d.root,session:d.root},{loadEvidence:()=>{touched++;}}),/AUTHORIZATION/);assert.equal(touched,0);});
test('LocalCheck performs no Google operation and grants no mutation',async t=>{const d=roots(t),e=evidence(d),r=await api.main(options(d),{loadEvidence:()=>e,loadTechnical:()=>technical(d),loadAttempt:()=>attempt(d),loadR2Attempt:()=>r2Attempt(d),claspEntry:()=>path.join(d.clasp,'bin.cjs'),native:()=>{throw new Error('native');}});assert.equal(r.status,'LOGREAD_WEBAPP_BROWSER_R3_LOCAL_CHECK_ONLY');assert.equal(r.retainedVersionNumber,10);assert.equal(r.versionCreationAuthorized,false);assert.equal(r.deploymentUpdateAuthorized,false);assert.equal(r.codePushAuthorized,false);assert.equal(r.googleReadAttempted,false);assert.equal(r.googleWriteAttempted,false);});
test('attempt loader accepts only the failed creation visibility result plus exact restoration',t=>{const d=roots(t),e=evidence(d),tech=technical(d),expected=attemptFixture(d,e,tech),a=api.loadAttempt(d.attempt,e,tech);assert.equal(a.failedResultSha256,expected.failed);assert.equal(a.restoredResultSha256,expected.restored);writeEvent(d.attempt,'WEBAPP_UPDATED_TO_10');assert.throws(()=>api.loadAttempt(d.attempt,e,tech),/UNSAFE_EVENT/);});
test('attempt loader refuses a release file or ambiguous result',t=>{const d=roots(t),e=evidence(d),tech=technical(d);attemptFixture(d,e,tech);fs.writeFileSync(path.join(d.attempt,'release-version.json'),'{}');assert.throws(()=>api.loadAttempt(d.attempt,e,tech),/RELEASE_FILE/);fs.rmSync(path.join(d.attempt,'release-version.json'));fs.writeFileSync(path.join(d.attempt,'result-'+crypto.randomUUID()+'.json'),'{}');assert.throws(()=>api.loadAttempt(d.attempt,e,tech),/AMBIGUOUS/);});
test('R3 binding carries all protected attempt hashes',t=>{const d=roots(t),b=api.binding(evidence(d),technical(d),attempt(d),r2Attempt(d));assert.equal(b.revision,'LOGREAD-webapp-browser-r3');assert.equal(b.attemptFailedResultSha256,hash('failed'));assert.equal(b.attemptRestoredResultSha256,hash('restored'));assert.equal(b.r2ResultSha256,hash('r2-result'));assert.equal(b.r2CanonicalInventorySha256,hash('r2-canonical'));assert.equal(b.candidateVersion,10);});
test('phase requires exactly retained version 10 and unchanged deployments',t=>{const d=roots(t),e=evidence(d);assert.equal(api.phase(v10(8),e).webAppVersion,8);assert.equal(api.phase(v10(10),e).webAppVersion,10);assert.throws(()=>api.phase(clone(baseline),e),/VERSION_10/);const wrong=v10();wrong.versions.at(-1).description='wrong';assert.throws(()=>api.phase(wrong,e),/VERSION_10/);});
test('phase rejects added deployment and unrelated drift',t=>{const d=roots(t),e=evidence(d),x=v10();x.deployments.push({deploymentId:'new',versionNumber:10});assert.throws(()=>api.phase(x,e),/DEPLOYMENT/);const y=v10();y.deployments[0].description='changed';assert.throws(()=>api.phase(y,e),/OTHER_DEPLOYMENT/);});
test('transport exposes no push, version creation, deployment creation or deletion',t=>{const d=roots(t),session=path.join(d.root,'session');fs.mkdirSync(session);const calls=[],run=(_n,args)=>{calls.push(args.slice(2));if(args[2]==='list-versions')return Buffer.from(JSON.stringify(v10().versions));if(args[2]==='list-deployments')return Buffer.from(JSON.stringify(v10().deployments));if(args[2]==='update-deployment')return Buffer.from(JSON.stringify({deploymentId:args[3],versionNumber:Number(args[5]),description:args[7]}));throw new Error('unexpected');};const io=api.makeTransport(path.join(d.clasp,'bin.cjs'),session,run);for(const key of ['push','createVersion','createDeployment','deleteDeployment'])assert.equal(io[key],undefined);assert.equal(io.updateDeployment('AKfycbx-OMcZ9gl',10,'Application Web').versionNumber,10);assert.deepEqual(calls,[['update-deployment','AKfycbx-OMcZ9gl','--versionNumber','10','--description','Application Web']]);});
test('version 10 verification stops before immutable pull if restored HEAD is not exact',t=>{const d=roots(t),e=evidence(d);let pulled=0;assert.throws(()=>api.verifyVersion10(e,{snapshot:()=>({files:cloneFiles(candidate),lists:v10()}),readVersion10:()=>{pulled++;}},()=>{}),/RESTORED_HEAD/);assert.equal(pulled,0);});
test('canonical version comparison accepts clasp gs/js suffix normalization only',()=>{const expected=[{name:'Code.gs',bytes:Buffer.from('same')},{name:'View.html',bytes:Buffer.from('view')}],pulled=[{name:'Code.js',bytes:Buffer.from('same')},{name:'View.html',bytes:Buffer.from('view')}];assert.equal(b0.sourceDigest(expected)===b0.sourceDigest(pulled),false);assert.equal(api.canonicalSourceExact(pulled,expected,2),true);pulled[0].bytes=Buffer.from('changed');assert.equal(api.canonicalSourceExact(pulled,expected,2),false);});
test('update and restoration touch only OMcZ9gl versions 8 and 10',t=>{const d=roots(t),e=evidence(d);let state=v10(8);const updates=[],io={lists:()=>clone(state),updateDeployment:(id,n,description)=>{updates.push({id,n,description});state=v10(n);return{deploymentId:id,versionNumber:n,description};}};api.updateWebApp(io,e,()=>{},()=>{});api.restoreWebApp(io,e,()=>{});assert.deepEqual(updates.map(x=>x.n),[10,8]);assert(updates.every(x=>x.id==='AKfycbx-OMcZ9gl'));});
test('historical verification has no write or repair path',t=>{const d=roots(t),e=evidence(d),events=[];api.verifyHistorical({snapshot:()=>({files:cloneFiles(backup),lists:v10(8)})},e,x=>events.push(x));assert.deepEqual(events,['RESTORED_EXACT','CODE_RESTORED']);assert.throws(()=>api.verifyHistorical({snapshot:()=>({files:cloneFiles(candidate),lists:v10(8)})},e,()=>{}),/HISTORICAL_HEAD/);});
test('manual protocol remains closed and recovery asks only required cleanup',async t=>{const d=roots(t),session=path.join(d.root,'manual');fs.mkdirSync(session);for(const event of ['AUDIT_CONNECTED_INTENT','LOGREAD_ACCESS_APPLIED_INTENT','PRIVATE_ACTIVATED_INTENT'])writeEvent(session,event);const asked=[],record=x=>writeEvent(session,x);await api.runSteps(session,async p=>{asked.push(p);return api.STEPS.find(x=>x.prompt===p).token;},record,true);assert.equal(asked.length,3);assert.deepEqual(api.STEPS.map(x=>x.event).slice(-3),['PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED']);});
test('full mocked Resume verifies v10, updates only deployment and restores without code push',async t=>{const d=roots(t),e=evidence(d),updates=[],answers=['LOGREAD-WEBAPP-BROWSER-R3-RESUME-AUTORISE-FERME',...api.STEPS.map(x=>x.token)],io={snapshot:()=>({files:cloneFiles(backup),lists:v10(8)}),lists:()=>v10(8),readVersion10:()=>({files:cloneFiles(candidate),lists:v10(8)}),updateDeployment:(id,n,description)=>{updates.push(n);return{deploymentId:id,versionNumber:n,description};}};const recordSteps=async(_s,ask,record)=>{const done=new Set();for(const step of api.STEPS){record(step.event+'_INTENT');assert.equal(await ask(step.prompt),step.token);record(step.event);done.add(step.event);}return done;};const r=await api.main({...options(d),mode:'Resume',output:path.join(d.root,'out'),authorization:api.AUTHORIZATION},{loadEvidence:()=>e,loadTechnical:()=>technical(d),loadAttempt:()=>attempt(d),loadR2Attempt:()=>r2Attempt(d),claspEntry:()=>path.join(d.clasp,'bin.cjs'),io,ask:async()=>answers.shift(),verifyVersion10:(_e,_io,record)=>record('VERSION_10_VERIFIED'),updateWebApp:(_io,_e,record)=>{record('WEBAPP_UPDATED_TO_10');updates.push(10);},restoreWebApp:(_io,_e,record)=>{record('WEBAPP_RESTORED_TO_8');updates.push(8);},verifyHistorical:(_io,_e,record)=>{record('RESTORED_EXACT');record('CODE_RESTORED');},runSteps:recordSteps});assert.equal(r.status,'RESTORED_WEBAPP_VERSION_8_VERSION_10_VERIFIED_BROWSER_REVIEW_REQUIRED');assert.equal(r.immutableVersion10Verified,true);assert.equal(r.newDeploymentCreated,false);assert.equal(r.codePushAttempted,false);assert.deepEqual(updates,[10,8]);});
test('wrong Resume phrase stops before output and Google',async t=>{const d=roots(t),e=evidence(d),out=path.join(d.root,'out');await assert.rejects(()=>api.main({...options(d),mode:'Resume',output:out,authorization:api.AUTHORIZATION},{loadEvidence:()=>e,loadTechnical:()=>technical(d),loadAttempt:()=>attempt(d),loadR2Attempt:()=>r2Attempt(d),claspEntry:()=>path.join(d.clasp,'bin.cjs'),ask:async()=>'NON'}),/OPERATOR/);assert.equal(fs.existsSync(out),false);});
test('safe errors redact arbitrary details',()=>{assert.equal(api.safeError(new Error('VERSION_10_CANONICAL_MISMATCH')),'VERSION_10_CANONICAL_MISMATCH');assert.equal(api.safeError(new Error('secret')),'LOGREAD_WEBAPP_BROWSER_R3_STOPPED');});
