'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const api=require('./validate-logread-browser-v2.cjs'),v1=require('./validate-logread-browser.cjs'),tech=require('./validate-logread.cjs'),b0=require('./prepare-d4b.cjs');
const clone=x=>structuredClone(x),files=[{name:'appsscript.json',bytes:Buffer.from('{}')},{name:'Base.gs',bytes:Buffer.from('base')}],candidate=[...files,{name:'New.gs',bytes:Buffer.from('new')}];
const baseline={versions:[{versionNumber:8,description:'old'}],deployments:[{deploymentId:'HEAD',description:'head'},{deploymentId:'OLD-OMcZ9gl',versionNumber:8,description:'portal'}]};
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'aks-v2-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const dirs={};for(const n of [api.PIN.campaign,api.PIN.readSession,api.PIN.technicalSession,api.PIN.priorSession,'clasp']){dirs[n]=path.join(root,n);fs.mkdirSync(dirs[n]);}fs.writeFileSync(path.join(dirs.clasp,'bin.cjs'),'');const e={dir:dirs[api.PIN.campaign],readSession:dirs[api.PIN.readSession],backup:files.map(f=>({...f,bytes:Buffer.from(f.bytes)})),candidate:candidate.map(f=>({...f,bytes:Buffer.from(f.bytes)})),lists:clone(baseline)};const technical={session:dirs[api.PIN.technicalSession],resultSha256:'d'.repeat(64)},prior={session:dirs[api.PIN.priorSession],restoredResultSha256:'e'.repeat(64)};const o={mode:'LocalCheck','package-run':e.dir,'read-session':e.readSession,'technical-session':technical.session,'prior-session':prior.session,'clasp-package':dirs.clasp,output:path.join(root,'out')};return{root,dirs,e,technical,prior,o};}
function model(e){let state=e.backup.map(f=>({...f,bytes:Buffer.from(f.bytes)})),lists=clone(e.lists),next=9,id='TEMP-ABCDEFG';const pushes=[];return{pushes,get listsState(){return lists;},snapshot(){return{files:state.map(f=>({...f,bytes:Buffer.from(f.bytes)})),lists:clone(lists)};},push(rows,label){pushes.push(label);state=rows.map(f=>({...f,bytes:Buffer.from(f.bytes)}));},lists(){return clone(lists);},createVersion(){lists.versions.push({versionNumber:next,description:api.VERSION_DESCRIPTION});return{versionNumber:next};},createDeployment(n){lists.deployments.push({deploymentId:id,versionNumber:n,description:api.DEPLOYMENT_DESCRIPTION});return{deploymentId:id,versionNumber:n,description:api.DEPLOYMENT_DESCRIPTION};},deleteDeployment(x){lists.deployments=lists.deployments.filter(d=>d.deploymentId!==x);return{deletedDeploymentIds:[x]};}};}
function record(session,event){fs.writeFileSync(path.join(session,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));}
function priorEvidence(f){fs.writeFileSync(path.join(f.prior.session,'session.json'),JSON.stringify({binding:v1.binding(f.e,f.technical)}));const common={revision:'LOGREAD-browser-r1',candidate:api.PIN.candidate,packageSha256:api.PIN.package,preflightSession:f.e.readSession,technicalSession:f.technical.session,technicalResultSha256:f.technical.resultSha256,localEvidenceVerified:true,googleReadAttempted:true,googleWriteAttempted:true,browserAuthorized:true,session:f.prior.session};fs.writeFileSync(path.join(f.prior.session,'result-00000000-0000-0000-0000-000000000001.json'),JSON.stringify({...common,status:'MANUAL_RECOVERY_REQUIRED',failure:'OPERATOR_STEP_NOT_CONFIRMED'}));fs.writeFileSync(path.join(f.prior.session,'result-00000000-0000-0000-0000-000000000002.json'),JSON.stringify({...common,status:'RESTORED_BROWSER_REVIEW_REQUIRED',failure:null}));for(const e of ['CANDIDATE_PUSH_INTENT','CANDIDATE_EXACT','AUDIT_CONNECTED','LOGREAD_PREFLIGHT_OK','LOGREAD_ACCESS_APPLIED','PRIVATE_ACTIVATED','OAUTH_REVIEWED_INTENT','PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED','RESTORE_PUSH_INTENT','RESTORED_EXACT','CODE_RESTORED'])record(f.prior.session,e);}
test('authorization is package bound and explicitly V2',()=>assert.equal(api.AUTHORIZATION,'LOGREAD-BROWSER-V2-'+api.PIN.package));
test('temporary version and deployment descriptions are closed',()=>{assert.match(api.VERSION_DESCRIPTION,/1645734f3b81/);assert.equal(api.DEPLOYMENT_DESCRIPTION,'ADMIN-006 D4-C LOG_READ temporary deployment');});
test('steps preserve manual cleanup order',()=>assert.deepEqual(api.STEPS.slice(-3).map(x=>x.event),['PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED']));
test('CLI refuses unknown, duplicate, unpaired and unauthorized arguments',t=>{const f=fixture(t),a=Object.entries(f.o).flatMap(([k,v])=>['--'+k,v]);assert.equal(api.parseArgs(a).mode,'LocalCheck');for(const x of [['--mode','LocalCheck'],['--target','x'],['--output']])assert.throws(()=>api.parseArgs([...a,...x]));assert.throws(()=>api.parseArgs(Object.entries({...f.o,mode:'Execute'}).flatMap(([k,v])=>['--'+k,v])));});
test('LocalCheck performs no native call and creates no output',async t=>{const f=fixture(t);let n=0;const r=await api.main(f.o,{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,claspEntry:()=>'',native:()=>n++});assert.equal(r.status,'LOGREAD_BROWSER_V2_LOCAL_CHECK_ONLY');assert.equal(n,0);assert.equal(fs.existsSync(f.o.output),false);});
test('execution authorization is checked before evidence',async t=>{const f=fixture(t);let n=0;await assert.rejects(()=>api.main({...f.o,mode:'Execute'},{loadEvidence:()=>n++}),/AUTHORIZATION/);assert.equal(n,0);});
test('prior attempt requires failure, exact restoration and no false browser pass',t=>{const f=fixture(t);priorEvidence(f);assert.equal(api.loadPriorAttempt(f.prior.session,f.e,f.technical).session,f.prior.session);record(f.prior.session,'MANAGER_BROWSER_PASS');assert.throws(()=>api.loadPriorAttempt(f.prior.session,f.e,f.technical),/FALSE_PASS/);});
test('phase accepts baseline, one described version and one matching temporary deployment',t=>{const f=fixture(t),m=model(f.e);assert.deepEqual(api.phase(m.lists(),f.e),{versionNumber:null,deploymentId:null});const v=m.createVersion().versionNumber;assert.deepEqual(api.phase(m.lists(),f.e,{versionNumber:v}),{versionNumber:9,deploymentId:null});const d=m.createDeployment(v);assert.equal(api.phase(m.lists(),f.e,{versionNumber:v,deploymentId:d.deploymentId}).deploymentId,d.deploymentId);});
test('phase refuses changed historical deployment',t=>{const f=fixture(t),x=clone(f.e.lists);x.deployments[1].versionNumber=7;assert.throws(()=>api.phase(x,f.e),/BASELINE/);});
test('phase refuses more than one added version',t=>{const f=fixture(t),x=clone(f.e.lists);x.versions.push({versionNumber:9,description:api.VERSION_DESCRIPTION},{versionNumber:10,description:api.VERSION_DESCRIPTION});assert.throws(()=>api.phase(x,f.e),/ADDITION/);});
test('transport emits only reviewed clasp 3.3 command shapes',t=>{const f=fixture(t),calls=[];const run=(_c,args)=>{calls.push(args);if(args[2]==='create-version')return Buffer.from('{"versionNumber":9}');if(args[2]==='create-deployment')return Buffer.from('{"deploymentId":"TEMP","versionNumber":9,"description":"'+api.DEPLOYMENT_DESCRIPTION+'"}');return Buffer.from('{"deletedDeploymentIds":["TEMP"]}');};const x=api.makeTransport('/entry',path.join(f.root,'native'),run);fs.mkdirSync(path.join(f.root,'native'));x.createVersion();x.createDeployment(9);x.deleteDeployment('TEMP');assert.deepEqual(calls.map(a=>a.slice(2)),[['create-version',api.VERSION_DESCRIPTION],['create-deployment','--versionNumber','9','--description',api.DEPLOYMENT_DESCRIPTION],['delete-deployment','TEMP']]);});
test('createRelease leaves original deployment untouched and reports URL locally',t=>{const f=fixture(t),m=model(f.e),s=fs.mkdirSync(path.join(f.root,'s'))||path.join(f.root,'s'),events=[],messages=[];const r=api.createRelease(m,f.e,s,e=>events.push(e),x=>messages.push(x));assert.equal(r.versionNumber,9);assert.ok(m.listsState.deployments.some(d=>d.deploymentId==='OLD-OMcZ9gl'&&d.versionNumber===8));assert.match(messages[0],/TEMP-ABCDEFG/);});
test('deleteTemporary removes only the temporary deployment and retains version',t=>{const f=fixture(t),m=model(f.e),s=path.join(f.root,'s');fs.mkdirSync(s);const r=api.createRelease(m,f.e,s,()=>{},()=>{});api.deleteTemporary(m,f.e,s,()=>{},r);assert.equal(m.listsState.versions.length,2);assert.deepEqual(m.listsState.deployments,f.e.lists.deployments);});
test('normal V2 flow removes deployment, restores code and retains one version',async t=>{const f=fixture(t),m=model(f.e),answers=['LOGREAD-BROWSER-V2-AUTORISE-FERME',...api.STEPS.map(s=>s.token)];const r=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,claspEntry:()=>'',io:m,ask:async()=>answers.shift(),notify:()=>{}});assert.equal(r.status,'RESTORED_TEMP_DEPLOYMENT_REMOVED_VERSION_RETAINED_REVIEW_REQUIRED');assert.equal(r.versionRetained,true);assert.equal(r.temporaryDeploymentRemoved,true);assert.deepEqual(m.listsState.deployments,f.e.lists.deployments);assert.equal(m.listsState.versions.length,2);assert.deepEqual(m.pushes,['browser-candidate-upload','v2-restore-upload']);});
test('manual failure preserves candidate and temporary deployment for recovery',async t=>{const f=fixture(t),m=model(f.e),answers=['LOGREAD-BROWSER-V2-AUTORISE-FERME',api.STEPS[0].token,api.STEPS[1].token,api.STEPS[2].token,api.STEPS[3].token,'NON'];const r=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,claspEntry:()=>'',io:m,ask:async()=>answers.shift(),notify:()=>{}});assert.equal(r.status,'MANUAL_RECOVERY_REQUIRED');assert.equal(m.listsState.deployments.length,3);assert.deepEqual(m.pushes,['browser-candidate-upload']);});
test('Restore closes manual state, deletes temporary deployment, restores code',async t=>{const f=fixture(t),m=model(f.e),a=['LOGREAD-BROWSER-V2-AUTORISE-FERME',api.STEPS[0].token,api.STEPS[1].token,api.STEPS[2].token,api.STEPS[3].token,'NON'];const first=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,claspEntry:()=>'',io:m,ask:async()=>a.shift(),notify:()=>{}});const b=['LOGREAD-BROWSER-V2-RESTAURATION-AUTORISEE','PRIVE-FERME','ACCESS-RESTAURE','AUDIT-DECONNECTE'];const second=await api.main({...f.o,mode:'Restore',session:first.session,authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,claspEntry:()=>'',io:m,ask:async()=>b.shift(),notify:()=>{}});assert.equal(second.status,'RESTORED_TEMP_DEPLOYMENT_REMOVED_VERSION_RETAINED_REVIEW_REQUIRED');assert.deepEqual(m.listsState.deployments,f.e.lists.deployments);assert.equal(m.listsState.versions.length,2);});
test('result exposes only temporary deployment suffix',async t=>{const f=fixture(t),m=model(f.e),answers=['LOGREAD-BROWSER-V2-AUTORISE-FERME',...api.STEPS.map(s=>s.token)];const r=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,claspEntry:()=>'',io:m,ask:async()=>answers.shift(),notify:()=>{}});assert.equal(r.temporaryDeploymentSuffix,'ABCDEFG');assert.equal(JSON.stringify(r).includes('TEMP-ABCDEFG'),false);});
test('arbitrary errors are redacted',()=>assert.equal(api.safeError(Error('https://secret.example/token')),'LOGREAD_BROWSER_V2_STOPPED'));
