'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const api=require('./validate-logread-browser-v4.cjs'),v2=require('./validate-logread-browser-v2.cjs'),v3=require('./validate-logread-browser-v3.cjs');
const files=[{name:'appsscript.json',bytes:Buffer.from('{}')},{name:'Base.gs',bytes:Buffer.from('base')}],candidate=[...files,{name:'New.gs',bytes:Buffer.from('new')}];
const baseline={versions:[{versionNumber:8,description:'old'}],deployments:[{deploymentId:'HEAD',description:'head'},{deploymentId:'OLD-OMcZ9gl',versionNumber:8,description:'ACCESS V1.4.0-rc.5'}]};
const copy=x=>x.map(f=>({...f,bytes:Buffer.from(f.bytes)})),clone=structuredClone;
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'aks-v4-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const dirs={};for(const n of [api.PIN.campaign,api.PIN.readSession,api.PIN.technicalSession,api.PIN.priorSession,api.PIN.v2Session,api.PIN.v3Session,'clasp']){dirs[n]=path.join(root,n);fs.mkdirSync(dirs[n]);}const e={dir:dirs[api.PIN.campaign],readSession:dirs[api.PIN.readSession],backup:copy(files),candidate:copy(candidate),lists:clone(baseline)},technical={session:dirs[api.PIN.technicalSession],resultSha256:'d'.repeat(64)},prior={session:dirs[api.PIN.priorSession],restoredResultSha256:'e'.repeat(64)},v2e={session:dirs[api.PIN.v2Session],restoredResultSha256:'f'.repeat(64)},v3e={session:dirs[api.PIN.v3Session],restoredResultSha256:'a'.repeat(64)},o={mode:'LocalCheck','package-run':e.dir,'read-session':e.readSession,'technical-session':technical.session,'prior-session':prior.session,'v2-session':v2e.session,'v3-session':v3e.session,'clasp-package':dirs.clasp,output:path.join(root,'out')};return{root,dirs,e,technical,prior,v2e,v3e,o};}
function model(e){let state=copy(e.backup),lists=clone(e.lists),calls=[];lists.versions.push({versionNumber:9,description:v2.VERSION_DESCRIPTION});return{calls,get listsState(){return lists;},snapshot(){return{files:copy(state),lists:clone(lists)};},push(rows,label){calls.push(['push',label]);state=copy(rows);},lists(){return clone(lists);},updateDeployment(id,n,d){calls.push(['update',id,n,d]);const row=lists.deployments.find(x=>x.deploymentId===id);Object.assign(row,{versionNumber:n,description:d,updateTime:'2026-09-04T12:00:00Z'});return clone(row);}};}
function record(session,event){fs.writeFileSync(path.join(session,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));}
function deps(f,m){return{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,loadV2Attempt:()=>f.v2e,loadV3Attempt:()=>f.v3e,claspEntry:()=>'',io:m,notify:()=>{}};}
function v3Evidence(f){fs.writeFileSync(path.join(f.v3e.session,'session.json'),JSON.stringify({binding:v3.binding(f.e,f.technical,f.prior,f.v2e)}));const common={revision:'LOGREAD-browser-v3-r1',candidate:api.PIN.candidate,packageSha256:api.PIN.package,preflightSession:f.e.readSession,technicalSession:f.technical.session,priorSession:f.prior.session,v2Session:f.v2e.session,v2RestoredResultSha256:f.v2e.restoredResultSha256,retainedVersionNumber:9,localEvidenceVerified:true,googleReadAttempted:true,googleWriteAttempted:true,browserAuthorized:true,versionCreationAuthorized:false,versionNumber:9,versionRetained:true,temporaryDeploymentSuffix:'feBNnyn',session:f.v3e.session};fs.writeFileSync(path.join(f.v3e.session,'result-00000000-0000-0000-0000-000000000001.json'),JSON.stringify({...common,status:'MANUAL_RECOVERY_REQUIRED',failure:'OPERATOR_STEP_NOT_CONFIRMED',temporaryDeploymentRemoved:false,originalDeploymentUnchanged:false}));fs.writeFileSync(path.join(f.v3e.session,'result-00000000-0000-0000-0000-000000000002.json'),JSON.stringify({...common,status:'RESTORED_TEMP_DEPLOYMENT_REMOVED_VERSION_9_RETAINED_REVIEW_REQUIRED',failure:null,temporaryDeploymentRemoved:true,originalDeploymentUnchanged:true}));for(const x of ['CANDIDATE_EXACT','TEMP_DEPLOYMENT_CREATED','PRIVATE_ACTIVATED','OAUTH_REVIEWED_INTENT','PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED','TEMP_DEPLOYMENT_DELETED','RESTORED_EXACT','CODE_RESTORED'])record(f.v3e.session,x);}
test('V4 pins retained version and existing Web App',()=>{assert.equal(api.PIN.baselineVersion,8);assert.equal(api.PIN.candidateVersion,9);assert.equal(api.PIN.deploymentSuffix,'OMcZ9gl');});
test('authorization remains package bound and forbids implicit execution',t=>{const f=fixture(t),args=Object.entries(f.o).flatMap(([k,v])=>['--'+k,v]);assert.equal(api.AUTHORIZATION,'LOGREAD-BROWSER-V4-'+api.PIN.package);assert.equal(api.parseArgs(args).mode,'LocalCheck');assert.throws(()=>api.parseArgs([...args,'--mode','Execute']),/INVALID_ARGUMENTS/);});
test('LocalCheck makes no native call or output write',async t=>{const f=fixture(t);let n=0;const r=await api.main(f.o,{...deps(f,null),io:undefined,native:()=>n++});assert.equal(r.status,'LOGREAD_BROWSER_V4_LOCAL_CHECK_ONLY');assert.equal(r.versionCreationAuthorized,false);assert.equal(r.deploymentCreationAuthorized,false);assert.equal(n,0);assert.equal(fs.existsSync(f.o.output),false);});
test('execution authorization is checked before evidence',async t=>{const f=fixture(t);let n=0;await assert.rejects(()=>api.main({...f.o,mode:'Execute'},{loadEvidence:()=>n++}),/AUTHORIZATION/);assert.equal(n,0);});
test('V3 evidence requires failed browser attempt and exact recovery',t=>{const f=fixture(t);v3Evidence(f);assert.equal(api.loadV3Attempt(f.v3e.session,f.e,f.technical,f.prior,f.v2e).session,f.v3e.session);record(f.v3e.session,'OAUTH_REVIEWED');assert.throws(()=>api.loadV3Attempt(f.v3e.session,f.e,f.technical,f.prior,f.v2e),/FALSE_BROWSER_PASS/);});
test('phase accepts only version 9 plus Web App on version 8 or 9',t=>{const f=fixture(t),m=model(f.e);assert.equal(api.phase(m.lists(),f.e).versionNumber,8);m.updateDeployment('OLD-OMcZ9gl',9,'ACCESS V1.4.0-rc.5');assert.equal(api.phase(m.lists(),f.e).versionNumber,9);});
test('phase accepts changed updateTime but refuses changed configuration',t=>{const f=fixture(t),m=model(f.e);m.updateDeployment('OLD-OMcZ9gl',9,'ACCESS V1.4.0-rc.5');assert.equal(api.phase(m.lists(),f.e).versionNumber,9);m.listsState.deployments.find(x=>x.deploymentId.endsWith('OMcZ9gl')).description='wrong';assert.throws(()=>api.phase(m.lists(),f.e),/CONFIGURATION/);});
test('phase refuses another deployment change',t=>{const f=fixture(t),m=model(f.e);m.listsState.deployments[0].description='changed';assert.throws(()=>api.phase(m.lists(),f.e),/OTHER_DEPLOYMENT/);});
test('phase refuses missing retained version 9',t=>{const f=fixture(t),m=model(f.e);m.listsState.versions.pop();assert.throws(()=>api.phase(m.lists(),f.e),/VERSION_9/);});
test('transport exposes update only and emits reviewed clasp shape',t=>{const f=fixture(t),calls=[];const run=(_c,args)=>{calls.push(args);return Buffer.from('{"deploymentId":"OLD-OMcZ9gl","versionNumber":9,"description":"ACCESS V1.4.0-rc.5"}');};const x=api.makeTransport('/entry',f.root,run);x.updateDeployment('OLD-OMcZ9gl',9,'ACCESS V1.4.0-rc.5');assert.equal(Object.hasOwn(x,'createVersion'),false);assert.equal(Object.hasOwn(x,'createDeployment'),false);assert.deepEqual(calls[0].slice(2),['update-deployment','OLD-OMcZ9gl','--versionNumber','9','--description','ACCESS V1.4.0-rc.5']);});
test('install pins baseline then reads candidate exactly',t=>{const f=fixture(t),m=model(f.e),events=[];api.install(f.e,m,x=>events.push(x));assert.deepEqual(m.calls,[['push','v4-candidate-upload']]);assert.ok(events.includes('CANDIDATE_EXACT'));});
test('update and restore touch only OMcZ9gl versions',t=>{const f=fixture(t),m=model(f.e),events=[];api.updateWebApp(m,f.e,x=>events.push(x),()=>{});assert.equal(api.phase(m.lists(),f.e).versionNumber,9);api.restoreWebApp(m,f.e,x=>events.push(x));assert.equal(api.phase(m.lists(),f.e).versionNumber,8);assert.deepEqual(m.calls.map(x=>x.slice(0,3)),[['update','OLD-OMcZ9gl',9],['update','OLD-OMcZ9gl',8]]);});
test('successful flow restores Web App and code without creation',async t=>{const f=fixture(t),m=model(f.e),answers=['LOGREAD-BROWSER-V4-AUTORISE-FERME',...v2.STEPS.map(x=>x.token)];const r=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{...deps(f,m),ask:async()=>answers.shift()});assert.equal(r.status,'RESTORED_WEBAPP_VERSION_8_VERSION_9_RETAINED_REVIEW_REQUIRED');assert.equal(r.webAppUpdatedToVersion9,true);assert.equal(r.webAppRestoredToVersion8,true);assert.equal(r.deploymentUpdateMetadataChanged,true);assert.equal(api.phase(m.lists(),f.e).versionNumber,8);assert.deepEqual(m.calls.map(x=>x[0]),['push','update','update','push']);});
test('manual stop leaves version 9 for reviewed recovery',async t=>{const f=fixture(t),m=model(f.e),answers=['LOGREAD-BROWSER-V4-AUTORISE-FERME',v2.STEPS[0].token,v2.STEPS[1].token,v2.STEPS[2].token,v2.STEPS[3].token,'NON'];const r=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{...deps(f,m),ask:async()=>answers.shift()});assert.equal(r.status,'MANUAL_RECOVERY_REQUIRED');assert.equal(api.phase(m.lists(),f.e).versionNumber,9);});
test('Restore closes manual state then restores version 8 and code',async t=>{const f=fixture(t),m=model(f.e),a=['LOGREAD-BROWSER-V4-AUTORISE-FERME',v2.STEPS[0].token,v2.STEPS[1].token,v2.STEPS[2].token,v2.STEPS[3].token,'NON'];const first=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{...deps(f,m),ask:async()=>a.shift()});const b=['LOGREAD-BROWSER-V4-RESTAURATION-AUTORISEE','PRIVE-FERME','ACCESS-RESTAURE','AUDIT-DECONNECTE'];const second=await api.main({...f.o,mode:'Restore',session:first.session,authorization:api.AUTHORIZATION},{...deps(f,m),ask:async()=>b.shift()});assert.equal(second.status,'RESTORED_WEBAPP_VERSION_8_VERSION_9_RETAINED_REVIEW_REQUIRED');assert.equal(api.phase(m.lists(),f.e).versionNumber,8);});
test('failure before manual state automatically restores Web App and code',async t=>{const f=fixture(t),m=model(f.e),update=m.updateDeployment.bind(m);let first=true;m.updateDeployment=(...args)=>{const out=update(...args);if(first){first=false;return{...out,description:'invalid-result'};}return out;};const r=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{...deps(f,m),ask:async()=>api.AUTHORIZATION.includes('V4')?'LOGREAD-BROWSER-V4-AUTORISE-FERME':''});assert.equal(r.status,'RESTORED_WEBAPP_VERSION_8_NOT_PASSED');assert.equal(api.phase(m.lists(),f.e).versionNumber,8);});
test('arbitrary errors are redacted',()=>assert.equal(api.safeError(Error('https://secret/token')),'LOGREAD_BROWSER_V4_STOPPED'));
