'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const api=require('./validate-logread-browser-v3.cjs'),v2=require('./validate-logread-browser-v2.cjs'),b0=require('./prepare-d4b.cjs');
const files=[{name:'appsscript.json',bytes:Buffer.from('{}')},{name:'Base.gs',bytes:Buffer.from('base')}],candidate=[...files,{name:'New.gs',bytes:Buffer.from('new')}],baseline={versions:[{versionNumber:8,description:'old'}],deployments:[{deploymentId:'HEAD',description:'head'},{deploymentId:'OLD-OMcZ9gl',versionNumber:8,description:'portal'}]};
const copyFiles=x=>x.map(f=>({...f,bytes:Buffer.from(f.bytes)})),clone=x=>structuredClone(x);
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'aks-v3-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const dirs={};for(const n of [api.PIN.campaign,api.PIN.readSession,api.PIN.technicalSession,api.PIN.priorSession,api.PIN.v2Session,'clasp']){dirs[n]=path.join(root,n);fs.mkdirSync(dirs[n]);}const e={dir:dirs[api.PIN.campaign],readSession:dirs[api.PIN.readSession],backup:copyFiles(files),candidate:copyFiles(candidate),lists:clone(baseline)},technical={session:dirs[api.PIN.technicalSession],resultSha256:'d'.repeat(64)},prior={session:dirs[api.PIN.priorSession],restoredResultSha256:'e'.repeat(64)},v2e={session:dirs[api.PIN.v2Session],restoredResultSha256:'f'.repeat(64)},o={mode:'LocalCheck','package-run':e.dir,'read-session':e.readSession,'technical-session':technical.session,'prior-session':prior.session,'v2-session':dirs[api.PIN.v2Session],'clasp-package':dirs.clasp,output:path.join(root,'out')};return{root,dirs,e,technical,prior,v2e,o};}
function model(e){let state=copyFiles(e.backup),lists=clone(e.lists);lists.versions.push({versionNumber:9,description:v2.VERSION_DESCRIPTION});const id='TEMP-1234567',pushes=[];return{pushes,get listsState(){return lists;},snapshot(){return{files:copyFiles(state),lists:clone(lists)};},push(rows,label){pushes.push(label);state=copyFiles(rows);},lists(){return clone(lists);},createDeployment(n){lists.deployments.push({deploymentId:id,versionNumber:n,description:v2.DEPLOYMENT_DESCRIPTION});return{deploymentId:id,versionNumber:n,description:v2.DEPLOYMENT_DESCRIPTION};},deleteDeployment(x){lists.deployments=lists.deployments.filter(d=>d.deploymentId!==x);return{deletedDeploymentIds:[x]};}};}
function record(session,event){fs.writeFileSync(path.join(session,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));}
function v2Evidence(f){fs.writeFileSync(path.join(f.v2e.session,'session.json'),JSON.stringify({binding:v2.binding(f.e,f.technical,f.prior)}));const common={revision:'LOGREAD-browser-v2-r1',candidate:api.PIN.candidate,packageSha256:api.PIN.package,preflightSession:f.e.readSession,technicalSession:f.technical.session,priorSession:f.prior.session,priorRestoredResultSha256:f.prior.restoredResultSha256,localEvidenceVerified:true,browserAuthorized:true,versionCreationAuthorized:true,session:f.v2e.session};fs.writeFileSync(path.join(f.v2e.session,'result-00000000-0000-0000-0000-000000000001.json'),JSON.stringify({...common,status:'RESTORE_REQUIRED',failure:'LOGREAD_BROWSER_V2_STOPPED',googleReadAttempted:true,googleWriteAttempted:true,versionNumber:null,originalDeploymentUnchanged:false}));fs.writeFileSync(path.join(f.v2e.session,'result-00000000-0000-0000-0000-000000000002.json'),JSON.stringify({...common,status:'RESTORED_VERSION_RETAINED_NOT_PASSED',failure:'LOGREAD_BROWSER_V2_STOPPED',googleReadAttempted:true,googleWriteAttempted:false,versionNumber:9,versionRetained:true,temporaryDeploymentSuffix:null,originalDeploymentUnchanged:true}));for(const x of ['CANDIDATE_PUSH_INTENT','CANDIDATE_EXACT','VERSION_CREATE_INTENT','RESTORE_PUSH_INTENT','RESTORED_EXACT','CODE_RESTORED'])record(f.v2e.session,x);}
test('authorization is V3 and package bound',()=>assert.equal(api.AUTHORIZATION,'LOGREAD-BROWSER-V3-'+api.PIN.package));
test('V3 pins and reuses version 9',()=>assert.equal(api.PIN.versionNumber,9));
test('CLI rejects unknown, duplicate and unauthorized execution',t=>{const f=fixture(t),a=Object.entries(f.o).flatMap(([k,v])=>['--'+k,v]);assert.equal(api.parseArgs(a).mode,'LocalCheck');assert.throws(()=>api.parseArgs([...a,'--mode','LocalCheck']));assert.throws(()=>api.parseArgs([...a,'--other','x']));assert.throws(()=>api.parseArgs(Object.entries({...f.o,mode:'Execute'}).flatMap(([k,v])=>['--'+k,v])));});
test('LocalCheck has no native call or output write',async t=>{const f=fixture(t);let n=0;const r=await api.main(f.o,{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,loadV2Attempt:()=>f.v2e,claspEntry:()=>'',native:()=>n++});assert.equal(r.status,'LOGREAD_BROWSER_V3_LOCAL_CHECK_ONLY');assert.equal(r.versionCreationAuthorized,false);assert.equal(n,0);assert.equal(fs.existsSync(f.o.output),false);});
test('execution authorization is checked before evidence',async t=>{const f=fixture(t);let n=0;await assert.rejects(()=>api.main({...f.o,mode:'Execute'},{loadEvidence:()=>n++}),/AUTHORIZATION/);assert.equal(n,0);});
test('V2 evidence requires stopped creation, version 9 recovery and exact code restore',t=>{const f=fixture(t);v2Evidence(f);assert.equal(api.loadV2Attempt(f.v2e.session,f.e,f.technical,f.prior).session,f.v2e.session);record(f.v2e.session,'TEMP_DEPLOYMENT_CREATED');assert.throws(()=>api.loadV2Attempt(f.v2e.session,f.e,f.technical,f.prior),/UNEXPECTED/);});
test('retainedPhase accepts version 9 and unchanged deployments',t=>{const f=fixture(t),m=model(f.e);assert.deepEqual(api.retainedPhase(m.lists(),f.e),{versionNumber:9,deploymentId:null});});
test('retainedPhase refuses missing version 9',t=>{const f=fixture(t);assert.throws(()=>api.retainedPhase(f.e.lists,f.e),/VERSION_9/);});
test('retainedPhase refuses altered version description',t=>{const f=fixture(t),m=model(f.e),x=m.lists();x.versions[1].description='wrong';assert.throws(()=>api.retainedPhase(x,f.e),/VERSION/);});
test('transport surface does not expose createVersion',t=>{const f=fixture(t);const x=api.makeTransport('/entry',path.join(f.root,'native'),()=>Buffer.from('[]'));fs.mkdirSync(path.join(f.root,'native'));assert.equal(Object.hasOwn(x,'createVersion'),false);});
test('install accepts baseline plus version 9 and restores candidate exactly',t=>{const f=fixture(t),m=model(f.e),events=[];api.install(f.e,m,e=>events.push(e));assert.deepEqual(m.pushes,['v3-candidate-upload']);assert.ok(events.includes('CANDIDATE_EXACT'));});
test('install refuses an existing temporary deployment',t=>{const f=fixture(t),m=model(f.e);m.createDeployment(9);assert.throws(()=>api.install(f.e,m,()=>{}),/HEAD_OR_INVENTORY/);assert.equal(m.pushes.length,0);});
test('temporary deployment uses only version 9 and leaves OMcZgl at 8',t=>{const f=fixture(t),m=model(f.e),s=path.join(f.root,'s');fs.mkdirSync(s);const r=api.createTemporary(m,f.e,s,()=>{},()=>{});assert.equal(r.versionNumber,9);assert.ok(m.listsState.deployments.some(d=>d.deploymentId==='OLD-OMcZ9gl'&&d.versionNumber===8));});
test('normal V3 flow removes temporary deployment, restores code and creates no version',async t=>{const f=fixture(t),m=model(f.e),answers=['LOGREAD-BROWSER-V3-AUTORISE-FERME',...v2.STEPS.map(s=>s.token)];const r=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,loadV2Attempt:()=>f.v2e,claspEntry:()=>'',io:m,ask:async()=>answers.shift(),notify:()=>{}});assert.equal(r.status,'RESTORED_TEMP_DEPLOYMENT_REMOVED_VERSION_9_RETAINED_REVIEW_REQUIRED');assert.equal(r.versionCreationAuthorized,false);assert.equal(m.listsState.versions.length,2);assert.deepEqual(m.listsState.deployments,f.e.lists.deployments);assert.deepEqual(m.pushes,['v3-candidate-upload','v3-restore-upload']);});
test('manual failure preserves temporary deployment for reviewed recovery',async t=>{const f=fixture(t),m=model(f.e),a=['LOGREAD-BROWSER-V3-AUTORISE-FERME',v2.STEPS[0].token,v2.STEPS[1].token,v2.STEPS[2].token,v2.STEPS[3].token,'NON'];const r=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,loadV2Attempt:()=>f.v2e,claspEntry:()=>'',io:m,ask:async()=>a.shift(),notify:()=>{}});assert.equal(r.status,'MANUAL_RECOVERY_REQUIRED');assert.equal(m.listsState.deployments.length,3);});
test('V3 Restore closes states, deletes deployment and restores code',async t=>{const f=fixture(t),m=model(f.e),a=['LOGREAD-BROWSER-V3-AUTORISE-FERME',v2.STEPS[0].token,v2.STEPS[1].token,v2.STEPS[2].token,v2.STEPS[3].token,'NON'];const first=await api.main({...f.o,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,loadV2Attempt:()=>f.v2e,claspEntry:()=>'',io:m,ask:async()=>a.shift(),notify:()=>{}});const b=['LOGREAD-BROWSER-V3-RESTAURATION-AUTORISEE','PRIVE-FERME','ACCESS-RESTAURE','AUDIT-DECONNECTE'];const second=await api.main({...f.o,mode:'Restore',session:first.session,authorization:api.AUTHORIZATION},{loadEvidence:()=>f.e,loadTechnical:()=>f.technical,loadPriorAttempt:()=>f.prior,loadV2Attempt:()=>f.v2e,claspEntry:()=>'',io:m,ask:async()=>b.shift(),notify:()=>{}});assert.equal(second.status,'RESTORED_TEMP_DEPLOYMENT_REMOVED_VERSION_9_RETAINED_REVIEW_REQUIRED');assert.deepEqual(m.listsState.deployments,f.e.lists.deployments);});
test('recovery without manual state does not require false cleanup confirmations',()=>{const done=new Set(['CANDIDATE_PUSH_INTENT']);assert.equal(api.cleanupComplete(done,true),true);});
test('arbitrary errors are redacted',()=>assert.equal(api.safeError(Error('https://secret/token')),'LOGREAD_BROWSER_V3_STOPPED'));
