'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const api=require('./validate-logread-webapp-browser.cjs'),prior=require('./validate-logread-webapp.cjs');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),clone=x=>structuredClone(x);
const baseline={versions:Array.from({length:9},(_,i)=>({versionNumber:i+1,description:'v'+(i+1)})),deployments:[{deploymentId:'AKfycbx-head',description:'Head deployment'},{deploymentId:'AKfycbx-OMcZ9gl',versionNumber:8,description:'Application Web'}]};
function roots(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'webapp-browser-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const dirs={root,packageDir:path.join(root,api.PIN.campaign),version8:path.join(root,api.PIN.version8Session),read:path.join(root,api.PIN.readSession),technical:path.join(root,api.PIN.technicalSession),clasp:path.join(root,'clasp')};for(const d of Object.values(dirs).slice(1))fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(dirs.clasp,'bin.cjs'),'');fs.writeFileSync(path.join(dirs.clasp,'package.json'),JSON.stringify({name:'@google/clasp',version:'3.3.0',bin:'bin.cjs'}));return dirs;}
function evidence(d){return{dir:d.packageDir,version8Session:d.version8,readSession:d.read,readReportSha256:hash('read'),candidate:[],backup:[],lists:clone(baseline)};}
function options(d){return{mode:'LocalCheck','package-run':d.packageDir,'version8-session':d.version8,'read-session':d.read,'technical-session':d.technical,'clasp-package':d.clasp};}
function version10(webAppVersion=8){const x=clone(baseline);x.versions.push({versionNumber:10,description:api.VERSION_DESCRIPTION});x.deployments.find(d=>d.deploymentId.endsWith('OMcZ9gl')).versionNumber=webAppVersion;return x;}
test('pins the corrected evidence and a distinct package-bound authorization',()=>{assert.equal(api.PIN.technicalSession,'logread-webapp-executor-Sk2Uvw');assert.equal(api.PIN.candidateVersion,10);assert.equal(api.AUTHORIZATION,'LOGREAD-WEBAPP-BROWSER-'+api.PIN.source);assert.match(api.VERSION_DESCRIPTION,/6a7d86300d90/);});
test('CLI is closed and LocalCheck cannot carry authority or output',t=>{const d=roots(t),o=options(d),args=Object.entries(o).flatMap(([k,v])=>['--'+k,v]);assert.equal(api.parseArgs(args).mode,'LocalCheck');for(const extra of [[ '--target','x'],['--output',d.root],['--authorization','x'],['--mode','LocalCheck']])assert.throws(()=>api.parseArgs([...args,...extra]));});
test('Execute and Restore reject missing exact authorization before evidence',async t=>{const d=roots(t),o=options(d);let touched=0;for(const mode of ['Execute','Restore'])await assert.rejects(()=>api.main({...o,mode,output:d.root,session:d.root},{loadEvidence:()=>{touched++;}}),/AUTHORIZATION/);assert.equal(touched,0);});
test('LocalCheck verifies identities but performs no Google operation',async t=>{const d=roots(t),e=evidence(d),tech={session:d.technical,resultSha256:hash('technical')};let native=0;const r=await api.main(options(d),{loadEvidence:()=>e,loadTechnical:()=>tech,claspEntry:()=>path.join(d.clasp,'bin.cjs'),native:()=>{native++;}});assert.equal(r.status,'LOGREAD_WEBAPP_BROWSER_LOCAL_CHECK_ONLY');assert.equal(r.plannedVersionNumber,10);assert.equal(r.baselineVersionsCount,9);assert.equal(r.baselineWebAppVersion,8);assert.equal(r.googleReadAttempted,false);assert.equal(r.googleWriteAttempted,false);assert.equal(r.versionCreationAuthorized,false);assert.equal(r.deploymentUpdateAuthorized,false);assert.equal(r.newDeploymentAuthorized,false);assert.equal(native,0);});
test('binding includes the package, preflight and successful technical result',t=>{const d=roots(t),e=evidence(d),b=api.binding(e,{session:d.technical,resultSha256:hash('technical')});assert.equal(b.revision,'LOGREAD-webapp-browser-r1');assert.equal(b.candidateVersion,10);assert.equal(b.baselineVersion,8);assert.equal(b.technicalResultSha256,hash('technical'));assert.equal(b.preflightReportSha256,e.readReportSha256);});
test('technical loader requires the one successful restored result and audit events',t=>{const d=roots(t),e=evidence(d);fs.writeFileSync(path.join(d.technical,'session.json'),JSON.stringify({binding:prior.sessionBinding(e)}));for(const event of ['OPERATOR_PRECONDITIONS_CONFIRMED','CANDIDATE_PUSH_INTENT','CANDIDATE_EXACT','TEST_PASS_OPERATOR_REPORTED','RESTORE_PUSH_INTENT','RESTORED_EXACT'])fs.writeFileSync(path.join(d.technical,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));const r={revision:'LOGREAD-webapp-executor-r1',target:'1quyIoxSMlxe6xpADPlxRxGikRF3OCTEid0-xhOHeSRZH0sU0AOeIRxs4',candidate:api.PIN.candidate,packageSha256:api.PIN.source,packageArchiveSha256:api.PIN.archive,packageReportSha256:api.PIN.packageReport,version8ReportSha256:api.PIN.version8Report,preflightReportSha256:e.readReportSha256,preflightSession:e.readSession,baselineVersionsCount:9,baselineDeploymentsCount:2,retainedVersionNumber:9,preflightSnapshotsVerifiedLocally:true,googleReadAttempted:true,googleWriteAttempted:true,propertiesOperatorConfirmed:true,secretContinuityOperatorConfirmed:true,browserDeploymentOperatorConfirmed:true,executionAuthorized:true,status:'RESTORED_TEST_PASS_OPERATOR_REVIEW_REQUIRED',testPassed:true,restoredExact:true,session:d.technical};const bytes=Buffer.from(JSON.stringify(r));fs.writeFileSync(path.join(d.technical,'result-'+crypto.randomUUID()+'.json'),bytes);assert.equal(api.loadTechnical(d.technical,e).resultSha256,hash(bytes));r.restoredExact=false;fs.writeFileSync(path.join(d.technical,'result-'+crypto.randomUUID()+'.json'),JSON.stringify(r));assert.throws(()=>api.loadTechnical(d.technical,e));});
test('phase accepts only baseline or exact retained version 10',t=>{const d=roots(t),e=evidence(d);assert.deepEqual(api.phase(clone(baseline),e),{versionNumber:null,deploymentId:'AKfycbx-OMcZ9gl',description:'Application Web',webAppVersion:8});assert.equal(api.phase(version10(8),e).versionNumber,10);assert.equal(api.phase(version10(10),e).webAppVersion,10);const wrong=version10();wrong.versions.at(-1).description='wrong';assert.throws(()=>api.phase(wrong,e),/VERSION_10/);});
test('phase rejects any new deployment or unrelated deployment drift',t=>{const d=roots(t),e=evidence(d),extra=version10();extra.deployments.push({deploymentId:'new',versionNumber:10});assert.throws(()=>api.phase(extra,e),/DEPLOYMENT/);const drift=version10();drift.deployments[0].description='changed';assert.throws(()=>api.phase(drift,e),/OTHER_DEPLOYMENT/);});
test('phase rejects a Web App target other than versions 8 and 10',t=>{const d=roots(t),e=evidence(d),x=version10();x.deployments[1].versionNumber=9;assert.throws(()=>api.phase(x,e),/WEBAPP_VERSION/);});
test('transport exposes no deployment creation or deletion path',t=>{const d=roots(t),session=path.join(d.root,'session');fs.mkdirSync(session);const calls=[],run=(_node,args,cwd)=>{calls.push(args.slice(2));const op=args[2];if(op==='list-versions')return Buffer.from(JSON.stringify(baseline.versions));if(op==='list-deployments')return Buffer.from(JSON.stringify(baseline.deployments));if(op==='create-version')return Buffer.from(JSON.stringify({versionNumber:10,description:api.VERSION_DESCRIPTION}));if(op==='update-deployment')return Buffer.from(JSON.stringify({deploymentId:args[3],versionNumber:Number(args[5]),description:args[7]}));throw new Error('unexpected');};const io=api.makeTransport(path.join(d.clasp,'bin.cjs'),session,run);assert.equal(io.createDeployment,undefined);assert.equal(io.deleteDeployment,undefined);assert.equal(io.createVersion().versionNumber,10);assert.equal(io.updateDeployment('AKfycbx-OMcZ9gl',10,'Application Web').versionNumber,10);assert.deepEqual(calls,[['create-version',api.VERSION_DESCRIPTION],['update-deployment','AKfycbx-OMcZ9gl','--versionNumber','10','--description','Application Web']]);});
test('deployment update is impossible until version 10 exists and Web App is on 8',t=>{const d=roots(t),e=evidence(d);let writes=0;assert.throws(()=>api.updateWebApp({lists:()=>clone(baseline),updateDeployment:()=>{writes++;}},e,()=>{},()=>{}),/NOT_READY/);assert.equal(writes,0);});
test('Web App update and restore preserve the same deployment and description',t=>{const d=roots(t),e=evidence(d);let state=version10(8);const updates=[],io={lists:()=>clone(state),updateDeployment:(id,n,description)=>{updates.push({id,n,description});state=version10(n);return{deploymentId:id,versionNumber:n,description};}};api.updateWebApp(io,e,()=>{},()=>{});api.restoreWebApp(io,e,()=>{});assert.deepEqual(updates,[{id:'AKfycbx-OMcZ9gl',n:10,description:'Application Web'},{id:'AKfycbx-OMcZ9gl',n:8,description:'Application Web'}]);});
test('manual protocol has the exact ten closed steps and recovery only asks cleanup',async t=>{const d=roots(t),session=path.join(d.root,'manual');fs.mkdirSync(session);assert.deepEqual(api.STEPS.map(x=>x.event),['AUDIT_CONNECTED','LOGREAD_PREFLIGHT_OK','LOGREAD_ACCESS_APPLIED','PRIVATE_ACTIVATED','OAUTH_REVIEWED','MANAGER_BROWSER_PASS','DENIED_BROWSER_PASS','PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED']);for(const event of ['AUDIT_CONNECTED_INTENT','LOGREAD_ACCESS_APPLIED_INTENT','PRIVATE_ACTIVATED_INTENT'])fs.writeFileSync(path.join(session,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));const asked=[],record=event=>fs.writeFileSync(path.join(session,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));await api.runSteps(session,async prompt=>{asked.push(prompt);return api.STEPS.find(x=>x.prompt===prompt).token;},record,true);assert.equal(asked.length,3);assert(api.cleanupComplete(new Set(['PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED']),false));});
test('safe errors do not disclose arbitrary exceptions',()=>{assert.equal(api.safeError(new Error('VERSION_10_SOURCE_MISMATCH')),'VERSION_10_SOURCE_MISMATCH');assert.equal(api.safeError(new Error('secret path')),'LOGREAD_WEBAPP_BROWSER_STOPPED');});
