'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const api=require('./validate-logread-browser.cjs'),tech=require('./validate-logread.cjs'),b0=require('./prepare-d4b.cjs');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const files=[{name:'appsscript.json',bytes:Buffer.from('{"runtimeVersion":"V8"}')},{name:'Base.gs',bytes:Buffer.from('base')}];
const candidate=[...files,{name:'New.gs',bytes:Buffer.from('new')}],lists={versions:[{versionNumber:8}],deployments:[{deploymentId:'portal',versionNumber:8}]};
const clone=x=>x.map(f=>({name:f.name,bytes:Buffer.from(f.bytes)}));
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'aks-browser-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const dirs={};for(const n of [api.PIN.campaign,api.PIN.readSession,api.PIN.technicalSession,'clasp'])dirs[n]=fs.mkdirSync(path.join(root,n))||path.join(root,n);fs.writeFileSync(path.join(dirs.clasp,'bin.cjs'),'');const evidence={dir:dirs[api.PIN.campaign],readSession:dirs[api.PIN.readSession],backup:clone(files),candidate:clone(candidate),lists};const technical={session:dirs[api.PIN.technicalSession],resultSha256:'a'.repeat(64)};const options={mode:'LocalCheck','package-run':evidence.dir,'read-session':evidence.readSession,'technical-session':technical.session,'clasp-package':dirs.clasp,output:path.join(root,'output')};return{root,dirs,evidence,technical,options};}
function io(e,h={}){let state=clone(e.backup),count=0;const pushes=[];return{pushes,get state(){return state;},snapshot(label){count++;let x={files:clone(state),lists:structuredClone(e.lists)};return h.snapshot?.({label,count,out:x})||x;},push(rows,label){pushes.push(label);state=clone(rows);}};}
function recordTo(session){return event=>fs.writeFileSync(path.join(session,'event-'+crypto.randomUUID()+'.json'),JSON.stringify({event}));}
test('authorization is exact and package bound',()=>assert.equal(api.AUTHORIZATION,'LOGREAD-BROWSER-'+api.PIN.package));
test('steps are closed, ordered and use unique events and tokens',()=>{assert.deepEqual(api.STEPS.map(s=>s.event),['AUDIT_CONNECTED','LOGREAD_PREFLIGHT_OK','LOGREAD_ACCESS_APPLIED','PRIVATE_ACTIVATED','OAUTH_REVIEWED','MANAGER_BROWSER_PASS','DENIED_BROWSER_PASS','PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED']);assert.equal(new Set(api.STEPS.map(s=>s.token)).size,api.STEPS.length);});
test('CLI refuses unknown, duplicate, unpaired and unauthorized modes',t=>{const f=fixture(t),args=Object.entries(f.options).flatMap(([k,v])=>['--'+k,v]);assert.equal(api.parseArgs(args).mode,'LocalCheck');for(const extra of [['--mode','LocalCheck'],['--target','x'],['--output']])assert.throws(()=>api.parseArgs([...args,...extra]));for(const mode of ['Execute','Restore'])assert.throws(()=>api.parseArgs(Object.entries({...f.options,mode}).flatMap(([k,v])=>['--'+k,v])));});
test('LocalCheck performs no native call or output write',async t=>{const f=fixture(t);let n=0;const r=await api.main(f.options,{loadEvidence:()=>f.evidence,loadTechnical:()=>f.technical,claspEntry:()=>'',native:()=>n++});assert.equal(r.status,'LOGREAD_BROWSER_LOCAL_CHECK_ONLY');assert.equal(n,0);assert.equal(fs.existsSync(f.options.output),false);});
test('execution authorization is checked before evidence',async t=>{const f=fixture(t);let touched=0;await assert.rejects(()=>api.main({...f.options,mode:'Execute'},{loadEvidence:()=>touched++}),/AUTHORIZATION/);assert.equal(touched,0);});
test('install reads current state, pushes candidate and reads it back',async t=>{const f=fixture(t),m=io(f.evidence),events=[];await api.install(f.evidence,m,e=>events.push(e));assert.deepEqual(m.pushes,['browser-candidate-upload']);assert.ok(events.includes('CANDIDATE_EXACT'));});
test('install refuses changed HEAD before push',async t=>{const f=fixture(t),m=io(f.evidence,{snapshot:({out,count})=>{if(count===1)out.files[1].bytes=Buffer.from('drift');return out;}});await assert.rejects(()=>api.install(f.evidence,m,()=>{}),/HEAD_CHANGED/);assert.equal(m.pushes.length,0);});
test('install refuses deployment inventory drift',async t=>{const f=fixture(t),m=io(f.evidence,{snapshot:({out,count})=>{if(count===1)out.lists.versions.push({versionNumber:9});return out;}});await assert.rejects(()=>api.install(f.evidence,m,()=>{}),/DEPLOYMENTS/);});
test('normal manual sequence records intent before every completion',async t=>{const f=fixture(t),session=fs.mkdirSync(path.join(f.root,'s'))||path.join(f.root,'s'),answers=api.STEPS.map(s=>s.token),seen=[];const done=await api.runSteps(session,async()=>answers.shift(),e=>{seen.push(e);recordTo(session)(e);});for(const s of api.STEPS){assert.ok(done.has(s.event));assert.ok(seen.indexOf(s.event+'_INTENT')<seen.indexOf(s.event));}});
test('wrong answer preserves mutation intent for recovery',async t=>{const f=fixture(t),session=fs.mkdirSync(path.join(f.root,'s'))||path.join(f.root,'s');await assert.rejects(()=>api.runSteps(session,async()=> 'NON',recordTo(session)),/OPERATOR/);assert.ok(api.runSteps);const ev=fs.readdirSync(session).map(n=>JSON.parse(fs.readFileSync(path.join(session,n))).event);assert.deepEqual(ev,['AUDIT_CONNECTED_INTENT']);});
test('recovery asks only cleanup required by recorded intents',async t=>{const f=fixture(t),session=fs.mkdirSync(path.join(f.root,'s'))||path.join(f.root,'s');for(const e of ['AUDIT_CONNECTED_INTENT','LOGREAD_ACCESS_APPLIED_INTENT','PRIVATE_ACTIVATED_INTENT'])recordTo(session)(e);const asked=[],answers=['PRIVE-FERME','ACCESS-RESTAURE','AUDIT-DECONNECTE'];const done=await api.runSteps(session,async p=>{asked.push(p);return answers.shift();},recordTo(session),true);assert.equal(asked.length,3);for(const e of ['PRIVATE_CLOSED','ACCESS_RESTORED','AUDIT_DISCONNECTED'])assert.ok(done.has(e));});
test('successful full flow restores code only after manual cleanup',async t=>{const f=fixture(t),m=io(f.evidence),answers=['LOGREAD-BROWSER-AUTORISE-FERME',...api.STEPS.map(s=>s.token)];const r=await api.main({...f.options,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.evidence,loadTechnical:()=>f.technical,claspEntry:()=>'',io:m,ask:async()=>answers.shift()});assert.equal(r.status,'RESTORED_BROWSER_REVIEW_REQUIRED');assert.deepEqual(m.pushes,['browser-candidate-upload','restore-upload']);assert.ok(r.completedEvents.includes('CODE_RESTORED'));});
test('failure after audit intent leaves candidate installed for manual recovery',async t=>{const f=fixture(t),m=io(f.evidence),answers=['LOGREAD-BROWSER-AUTORISE-FERME','NON'];const r=await api.main({...f.options,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.evidence,loadTechnical:()=>f.technical,claspEntry:()=>'',io:m,ask:async()=>answers.shift()});assert.equal(r.status,'MANUAL_RECOVERY_REQUIRED');assert.deepEqual(m.pushes,['browser-candidate-upload']);assert.ok(r.completedEvents.includes('AUDIT_CONNECTED_INTENT'));});
test('failure before any manual mutation restores candidate automatically',async t=>{const f=fixture(t),m=io(f.evidence,{snapshot:({out,count})=>{if(count===2)out.files[1].bytes=Buffer.from('bad');return out;}}),answers=['LOGREAD-BROWSER-AUTORISE-FERME'];const r=await api.main({...f.options,mode:'Execute',authorization:api.AUTHORIZATION},{loadEvidence:()=>f.evidence,loadTechnical:()=>f.technical,claspEntry:()=>'',io:m,ask:async()=>answers.shift()});assert.equal(r.status,'RESTORED_BROWSER_NOT_PASSED');assert.deepEqual(m.pushes,['browser-candidate-upload','restore-upload']);});
test('technical evidence requires exact restored result and event chain',t=>{const f=fixture(t),s=f.technical.session;fs.writeFileSync(path.join(s,'session.json'),JSON.stringify({binding:tech.sessionBinding(f.evidence)}));const result={revision:'LOGREAD-executor-r1',target:b0.TARGET,candidate:api.PIN.candidate,packageSha256:api.PIN.package,packageArchiveSha256:api.PIN.packageArchive,packageReportSha256:api.PIN.packageReport,backupArchiveSha256:api.PIN.archive,preflightSession:f.evidence.readSession,preflightSnapshotsVerifiedLocally:true,googleReadAttempted:true,googleWriteAttempted:true,propertiesOperatorConfirmed:true,executionAuthorized:true,status:'RESTORED_TEST_PASS_OPERATOR_REVIEW_REQUIRED',testPassed:true,restoredExact:true,session:s};fs.writeFileSync(path.join(s,'result-00000000-0000-0000-0000-000000000000.json'),JSON.stringify(result));for(const event of ['CANDIDATE_PUSH_INTENT','CANDIDATE_EXACT','TEST_PASS_OPERATOR_REPORTED','RESTORED_EXACT'])recordTo(s)(event);assert.equal(api.loadTechnical(s,f.evidence).session,s);result.restoredExact=false;fs.writeFileSync(path.join(s,'result-00000000-0000-0000-0000-000000000000.json'),JSON.stringify(result));assert.throws(()=>api.loadTechnical(s,f.evidence),/TECHNICAL_RESULT/);});
test('arbitrary errors are redacted',()=>assert.equal(api.safeError(Error('https://secret/token')),'LOGREAD_BROWSER_STOPPED'));
